POST http://3.209.12.36:8000/api/account/login
Content-Type: application/json

{
    "username": "Buttercup",
    "password": "12345678"
}

###

GET http://3.209.12.36:8000/api/account/properties
Content-Type: application/json
Authorization: Token edeb37e8dbf86eaa841a0368a4e39ab5ab54ae38

###

POST http://3.209.12.36:8000/api/account/register
Content-Type: application/json

{
    "username": "amiga",
    "email": "amiga@gmail.com",
    "password": "amiga9",
    "password2": "amiga9"
}

###

GET http://3.209.12.36:8000/logout
Content-Type: application/json
Authorization: Token 44fd62b5efa94830702617623ae71899e983c608

###
POST http://3.209.12.36:8000/api/account/send_request
Content-Type: application/json
Authorization: Token a79af587288185f784c87b870a43a6140aad3d61

{
    "from_user": "2",
    "to_user": "32"
}

###

POST http://3.209.12.36:8000/api/account/get_friend_requests
Content-Type: application/json
Authorization: Token a79af587288185f784c87b870a43a6140aad3d61

{
    "to_user": "32"
}

